/**
 * Created by Chile on 2/26/2016.
 */
function getLanguageFromWikicode(code)
{
    var langmap = {
            "aa": "Afar",
            "ab": "Abkhazian",
            "ace": "Acehnese",
            "af": "Afrikaans",
            "ak": "Akan",
            "als": "Alemannic",
            "am": "Amharic",
            "an": "Aragonese",
            "ang": "Anglo-Saxon",
            "ar": "Arabic",
            "arc": "Assyrian Neo-Aramaic",
            "arz": "Egyptian Arabic",
            "as": "Assamese",
            "ast": "Asturian",
            "av": "Avar",
            "ay": "Aymara",
            "az": "Azerbaijani",
            "ba": "Bashkir",
            "bar": "Bavarian",
            "bat-smg": "Samogitian",
            "bcl": "Central_Bicolano",
            "be": "Belarusian",
            "be-x-old": "Belarusian",
            "bg": "Bulgarian",
            "bh": "Bihari",
            "bi": "Bislama",
            "bjn": "Banjar",
            "bm": "Bambara",
            "bn": "Bengali",
            "bo": "Tibetan",
            "bpy": "Bishnupriya Manipuri",
            "br": "Breton",
            "bs": "Bosnian",
            "bug": "Buginese",
            "bxr": "Buryat ",
            "ca": "Catalan",
            "cbk-zam": "Zamboanga Chavacano",
            "cdo": "Min Dong",
            "ce": "Chechen",
            "ceb": "Cebuano",
            "ch": "Chamorro",
            "cho": "Choctaw",
            "chr": "Cherokee",
            "chy": "Cheyenne",
            "ckb": "Sorani",
            "co": "Corsican",
            "commons": "commons",
            "cr": "Cree",
            "crh": "Crimean Tatar",
            "cs": "Czech",
            "csb": "Kashubian",
            "cu": "Old Church Slavonic",
            "cv": "Chuvash",
            "cy": "Welsh",
            "da": "Danish",
            "de": "German",
            "diq": "Zazaki",
            "dsb": "Lower Sorbian",
            "dv": "Divehi",
            "dz": "Dzongkha",
            "ee": "Ewe",
            "el": "Greek",
            "eml": "Emilian-Romagnol",
            "en": "English",
            "eo": "Esperanto",
            "es": "Spanish",
            "et": "Estonian",
            "eu": "Basque",
            "ext": "Extremaduran",
            "fa": "Persian",
            "ff": "Fula",
            "fi": "Finnish",
            "fiu-vro": "V",
            "fj": "Fijian",
            "fo": "Faroese",
            "fr": "French",
            "frp": "Franco-Proven",
            "frr": "North Frisian",
            "fur": "Friulian",
            "fy": "West Frisian",
            "ga": "Irish",
            "gag": "Gagauz",
            "gan": "Gan",
            "gd": "Scottish Gaelic",
            "gl": "Galician",
            "glk": "Gilaki",
            "gn": "Guarani",
            "got": "Gothic",
            "gu": "Gujarati",
            "gv": "Manx",
            "ha": "Hausa",
            "hak": "Hakka",
            "haw": "Hawaiian",
            "he": "Hebrew",
            "hi": "Hindi",
            "hif": "Fiji Hindi",
            "ho": "Hiri Motu",
            "hr": "Croatian",
            "hsb": "Upper Sorbian",
            "ht": "Haitian",
            "hu": "Hungarian",
            "hy": "Armenian",
            "hz": "Herero",
            "ia": "Interlingua",
            "id": "Indonesian",
            "ie": "Interlingue",
            "ig": "Igbo",
            "ii": "Sichuan Yi",
            "ik": "Inupiak",
            "ilo": "Ilokano",
            "io": "Ido",
            "is": "Icelandic",
            "it": "Italian",
            "iu": "Inuktitut",
            "ja": "Japanese",
            "jbo": "Lojban",
            "jv": "Javanese",
            "ka": "Georgian",
            "kaa": "Karakalpak",
            "kab": "Kabyle",
            "kbd": "Kabardian Circassian",
            "kg": "Kongo",
            "ki": "Kikuyu",
            "kj": "Kuanyama",
            "kk": "Kazakh",
            "kl": "Greenlandic",
            "km": "Khmer",
            "kn": "Kannada",
            "ko": "Korean",
            "koi": "Komi-Permyak",
            "kr": "Kanuri",
            "krc": "Karachay-Balkar",
            "ks": "Kashmiri",
            "ksh": "Ripuarian",
            "ku": "Kurdish",
            "kv": "Komi",
            "kw": "Cornish",
            "ky": "Kirghiz",
            "la": "Latin",
            "lad": "Ladino",
            "lb": "Luxembourgish",
            "lbe": "Lak",
            "lez": "Lezgian",
            "lg": "Luganda",
            "li": "Limburgian",
            "lij": "Ligurian",
            "lmo": "Lombard",
            "ln": "Lingala",
            "lo": "Lao",
            "lt": "Lithuanian",
            "ltg": "Latgalian",
            "lv": "Latvian",
            "map-bms": "Banyumasan",
            "mdf": "Moksha",
            "mg": "Malagasy",
            "mh": "Marshallese",
            "mhr": "Meadow Mari",
            "mi": "Maori",
            "mk": "Macedonian",
            "ml": "Malayalam",
            "mn": "Mongolian",
            "mo": "Moldovan",
            "mr": "Marathi",
            "mrj": "Hill Mari",
            "ms": "Malay",
            "mt": "Maltese",
            "mus": "Muscogee",
            "mwl": "Mirandese",
            "my": "Burmese",
            "myv": "Erzya",
            "mzn": "Mazandarani",
            "na": "Nauruan",
            "nah": "Nahuatl",
            "nap": "Neapolitan",
            "nds": "Low Saxon",
            "nds-nl": "Dutch Low Saxon",
            "ne": "Nepali",
            "new": "Newar",
            "ng": "Ndonga",
            "nl": "Dutch",
            "nn": "Norwegian ",
            "no": "Norwegian ",
            "nov": "Novial",
            "nrm": "Norman",
            "nso": "Northern Sotho",
            "nv": "Navajo",
            "ny": "Chichewa",
            "oc": "Occitan",
            "om": "Oromo",
            "or": "Oriya",
            "os": "Ossetian",
            "pa": "Punjabi",
            "pag": "Pangasinan",
            "pam": "Kapampangan",
            "pap": "Papiamentu",
            "pcd": "Picard",
            "pdc": "Pennsylvania German",
            "pfl": "Palatinate German",
            "pi": "Pali",
            "pih": "Norfolk",
            "pl": "Polish",
            "pms": "Piedmontese",
            "pnb": "Western Panjabi",
            "pnt": "Pontic",
            "ps": "Pashto",
            "pt": "Portuguese",
            "qu": "Quechua",
            "rm": "Romansh",
            "rmy": "Romani",
            "rn": "Kirundi",
            "ro": "Romanian",
            "roa-rup": "Aromanian",
            "roa-tara": "Tarantino",
            "ru": "Russian",
            "rue": "Rusyn",
            "rw": "Kinyarwanda",
            "sa": "Sanskrit",
            "sah": "Sakha",
            "sc": "Sardinian",
            "scn": "Sicilian",
            "sco": "Scots",
            "sd": "Sindhi",
            "se": "Northern Sami",
            "sg": "Sango",
            "sh": "Serbo-Croatian",
            "si": "Sinhalese",
            "simple": "Simple English",
            "sk": "Slovak",
            "sl": "Slovenian",
            "sm": "Samoan",
            "sn": "Shona",
            "so": "Somali",
            "sq": "Albanian",
            "sr": "Serbian",
            "srn": "Sranan",
            "ss": "Swati",
            "st": "Sesotho",
            "stq": "Saterland Frisian",
            "su": "Sundanese",
            "sv": "Swedish",
            "sw": "Swahili",
            "szl": "Silesian",
            "ta": "Tamil",
            "te": "Telugu",
            "tet": "Tetum",
            "tg": "Tajik",
            "th": "Thai",
            "ti": "Tigrinya",
            "tk": "Turkmen",
            "tl": "Tagalog",
            "tn": "Tswana",
            "to": "Tongan",
            "tpi": "Tok Pisin",
            "tr": "Turkish",
            "ts": "Tsonga",
            "tt": "Tatar",
            "tum": "Tumbuka",
            "tw": "Twi",
            "ty": "Tahitian",
            "udm": "Udmurt",
            "ug": "Uyghur",
            "uk": "Ukrainian",
            "ur": "Urdu",
            "uz": "Uzbek",
            "ve": "Venda",
            "vec": "Venetian",
            "vep": "Vepsian",
            "vi": "Vietnamese",
            "vls": "West Flemish",
            "vo": "Volap",
            "wa": "Walloon",
            "war": "Waray-Waray",
            "wikidata": "Wikidata",
            "wo": "Wolof",
            "wuu": "Wu",
            "xal": "Kalmyk",
            "xh": "Xhosa",
            "xmf": "Mingrelian",
            "yi": "Yiddish",
            "yo": "Yoruba",
            "za": "Zhuang",
            "zea": "Zeelandic",
            "zh": "Chinese",
            "zh-classical": "Classical Chinese",
            "zh-min-nan": "Min Nan",
            "zh-yue": "Cantonese",
            "zu": "Zulu"
        };
        return langmap[code.replace(/_/g,'-')];
}