package org.dbpedia.extraction.wikiparser.impl.wikipedia

import org.dbpedia.extraction.util.Language

/**
 * Holds the category redirect identifiers of the different Wikipedia languages. Do not edit CategoryRedirect.scala!
 * GenerateWikiSettings.scala uses the template file CategoryRedirect.scala.txt to generate CategoryRedirect.scala.
 */
object CategoryRedirect
{
    private val map : Map[String, Set[String]] =
    Map("ka"->ka_categoryRedirects,"el"->el_categoryRedirects,"arz"->arz_categoryRedirects,"sco"->sco_categoryRedirects,"sd"->sd_categoryRedirects,"bn"->bn_categoryRedirects,"ps"->ps_categoryRedirects,"bs"->bs_categoryRedirects,"ceb"->ceb_categoryRedirects,"en"->en_categoryRedirects,"zh"->zh_categoryRedirects,"ar"->ar_categoryRedirects,"tl"->tl_categoryRedirects,"eu"->eu_categoryRedirects,"my"->my_categoryRedirects,"uk"->uk_categoryRedirects,"sh"->sh_categoryRedirects,"bh"->bh_categoryRedirects,"da"->da_categoryRedirects,"gv"->gv_categoryRedirects,"zh-min-nan"->zh_min_nan_categoryRedirects,"ckb"->ckb_categoryRedirects,"ur"->ur_categoryRedirects,"es"->es_categoryRedirects,"si"->si_categoryRedirects,"ko"->ko_categoryRedirects,"fr"->fr_categoryRedirects,"sr"->sr_categoryRedirects,"nn"->nn_categoryRedirects,"mr"->mr_categoryRedirects,"sv"->sv_categoryRedirects,"sa"->sa_categoryRedirects,"hi"->hi_categoryRedirects,"sl"->sl_categoryRedirects,"simple"->simple_categoryRedirects,"gu"->gu_categoryRedirects,"arc"->arc_categoryRedirects,"yi"->yi_categoryRedirects,"mt"->mt_categoryRedirects,"kn"->kn_categoryRedirects,"mwl"->mwl_categoryRedirects,"lmo"->lmo_categoryRedirects,"as"->as_categoryRedirects,"cs"->cs_categoryRedirects,"or"->or_categoryRedirects,"ro"->ro_categoryRedirects,"ms"->ms_categoryRedirects,"ja"->ja_categoryRedirects,"ca"->ca_categoryRedirects,"ilo"->ilo_categoryRedirects,"fa"->fa_categoryRedirects,"so"->so_categoryRedirects,"ta"->ta_categoryRedirects,"mk"->mk_categoryRedirects,"id"->id_categoryRedirects,"diq"->diq_categoryRedirects,"vi"->vi_categoryRedirects,"ku"->ku_categoryRedirects,"ace"->ace_categoryRedirects,"tr"->tr_categoryRedirects,"zh-yue"->zh_yue_categoryRedirects,"sq"->sq_categoryRedirects,"eo"->eo_categoryRedirects,"th"->th_categoryRedirects,"hu"->hu_categoryRedirects,"ne"->ne_categoryRedirects,"gl"->gl_categoryRedirects,"pt"->pt_categoryRedirects,"no"->no_categoryRedirects,"ml"->ml_categoryRedirects,"qu"->qu_categoryRedirects,"ga"->ga_categoryRedirects,"lv"->lv_categoryRedirects)
    private def ka_categoryRedirects = Set("კატეგორიის გადამისამართება")
    private def el_categoryRedirects = Set("Category redirect")
    private def arz_categoryRedirects = Set("تحويل تصنيف")
    private def sco_categoryRedirects = Set("Category redirect")
    private def sd_categoryRedirects = Set("واپس منتقل زمرو","Category redirect")
    private def bn_categoryRedirects = Set("বিষয়শ্রেণী পুনর্নির্দেশ","বিষয়শ্রেণী পুননির্দেশ")
    private def ps_categoryRedirects = Set("Category redirect")
    private def bs_categoryRedirects = Set("Category redirect")
    private def ceb_categoryRedirects = Set("Category redirect")
    private def en_categoryRedirects = Set("Categoryredirect","Category move","Cat red","Catredirect","Cat redir","Category Redirect","Cat redirect","Catr","Category redirect","Catred","Cat move","Catredir")
    private def zh_categoryRedirects = Set("Categoryredirect","重定向分类","分类重定向","Catredirect","Seecat","分類重定向","Category redirect","Cat-redirect","CR","Cr","See cat")
    private def ar_categoryRedirects = Set("نقل تصنيف","تحويل التصنيف","تحويلة تصنيف","تحويل تصنيف","Category redirect")
    private def tl_categoryRedirects = Set("Category redirect")
    private def eu_categoryRedirects = Set("Kategoria birzuzendu","Kategoria redirect")
    private def my_categoryRedirects = Set("Category redirect")
    private def uk_categoryRedirects = Set("Categoryredirect","Redirect category","Category redirect","Catredirect")
    private def sh_categoryRedirects = Set("Preusmeri kategoriju","Catredirect","Category redirect","Preusmjeri kategoriju","Catred","Kategorija nije u upotrebi","Prekategorizuj","Prekat")
    private def bh_categoryRedirects = Set("श्रेणी अनुप्रेषित","अनुश्रे","Catr","Category redirect","Catred","श्रेणीअनुप्रेषित","श्रेअनु","अनुप्रेषित श्रेणी")
    private def da_categoryRedirects = Set("Kategoriomdirigering")
    private def gv_categoryRedirects = Set("Aastiurey ronney")
    private def zh_min_nan_categoryRedirects = Set("Khì-hiâm-lūi","Category redirect")
    private def ckb_categoryRedirects = Set("ڕەوانەکەری پۆل")
    private def ur_categoryRedirects = Set("زمرہ رجوع مکرر","Category redirect")
    private def es_categoryRedirects = Set("Categoría redirigida","Category redirect","Catred")
    private def si_categoryRedirects = Set("ප්‍රවර්ග යලි යොමු","Category redirect")
    private def ko_categoryRedirects = Set("분류 넘겨주기","분류넘겨주기","분넘")
    private def fr_categoryRedirects = Set("Catégorie redirigée","Redirection de catégorie")
    private def sr_categoryRedirects = Set("Category redirect")
    private def nn_categoryRedirects = Set("Kategoriomdirigering")
    private def mr_categoryRedirects = Set("वर्ग पुनर्निर्देशन","Category redirect")
    private def sv_categoryRedirects = Set("Kategoriomdirigering","Omdirigering kategori","Seecat")
    private def sa_categoryRedirects = Set("Category redirect")
    private def hi_categoryRedirects = Set("Categoryredirect","श्रेणी अनुप्रेषित","Cat redirect","Category redirect","श्रेणीअनुप्रेषित")
    private def sl_categoryRedirects = Set("Preusmeritev kategorije","Category redirect")
    private def simple_categoryRedirects = Set("Category redirect","Catredirect","Categoryredirect")
    private def gu_categoryRedirects = Set("Category redirect")
    private def arc_categoryRedirects = Set("Category redirect")
    private def yi_categoryRedirects = Set("קאטעגאריע אריבערפירן")
    private def mt_categoryRedirects = Set("Rindirizzament kategorija")
    private def kn_categoryRedirects = Set("ವರ್ಗ redirect")
    private def mwl_categoryRedirects = Set("Ancaminamiento de catadorie","Redirecionamiento de catadorie")
    private def lmo_categoryRedirects = Set("Category redirect")
    private def as_categoryRedirects = Set("Category redirect")
    private def cs_categoryRedirects = Set("Zastaralá kategorie")
    private def or_categoryRedirects = Set("Category redirect")
    private def ro_categoryRedirects = Set("Redirect category","RedCat","Redcat","Red cat","Rc","Seecat","RedirCat","Category redirect","Redirect categorie","Redirecționare categorie")
    private def ms_categoryRedirects = Set("Pengalihan kategori","Category redirect","Categoryredirect")
    private def ja_categoryRedirects = Set("Category redirect","Categoryredirect")
    private def ca_categoryRedirects = Set("Categoria redirigida","Category redirect")
    private def ilo_categoryRedirects = Set("Kategoria a baw-ing","Category redirect")
    private def fa_categoryRedirects = Set("رده بهتر","Category redirect")
    private def so_categoryRedirects = Set("Category redirect")
    private def ta_categoryRedirects = Set("Category redirect")
    private def mk_categoryRedirects = Set("Премести категорија","Катпремести","КатПремести")
    private def id_categoryRedirects = Set("Alihkategori","Category redirect","Alih kat","Alih kategori","Alihkat")
    private def diq_categoryRedirects = Set("Category redirect","Categoryredirect")
    private def vi_categoryRedirects = Set("Categoryredirect","Catredirect","Catr","Category redirect","Chuyển hướng thể loại","Thể loại đổi hướng","Đhtl","Catred","Đổi hướng thể loại")
    private def ku_categoryRedirects = Set("Category redirect")
    private def ace_categoryRedirects = Set("Category redirect")
    private def tr_categoryRedirects = Set("Redirect category","Kategori taşıma","Kat redir","Seecat","Kategori yönlendirme")
    private def zh_yue_categoryRedirects = Set("分類彈去","Category redirect","分類跳轉","Cr")
    private def sq_categoryRedirects = Set("Kategori e zhvendosur","Category redirect")
    private def eo_categoryRedirects = Set("Kategoria alidirekto")
    private def th_categoryRedirects = Set("เปลี่ยนทางหมวดหมู่","Category redirect")
    private def hu_categoryRedirects = Set("Kat-redir","Katredir","Kat-redirekt")
    private def ne_categoryRedirects = Set("श्रेणी अनुप्रेषण")
    private def gl_categoryRedirects = Set("Redirección de categoría")
    private def pt_categoryRedirects = Set("Redirect-categoria","Category redirect","Redircat","Redirecionamento de categorias","Redirecionamento de categoria")
    private def no_categoryRedirects = Set("Kategoriomdirigering","Kategori-omdirigering","Category redirect","K")
    private def ml_categoryRedirects = Set("Category redirect")
    private def qu_categoryRedirects = Set("CR")
    private def ga_categoryRedirects = Set("Category redirect")
    private def lv_categoryRedirects = Set("Kat pāradresācija")


// mo - URL 'https://mo.wikipedia.org/w/api.php?action=query&format=xml&meta=siteinfo&siprop=namespaces|namespacealiases|magicwords|interwikimap&continue=' replied 301 Moved Permanently - Location: 'https://ro.wikipedia.org/wiki/Pagina_principală?action=query&format=xml&meta=siteinfo&siprop=namespaces|namespacealiases|magicwords|interwikimap&continue='

    def apply(language : Language): Set[String] = map(language.wikiCode)

    def get(language : Language) : Option[Set[String]] = map.get(language.wikiCode)
}
