name: Update Minidump document

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
          # needed for Wikimedia API calls to not get a 403
          JAVA_TOOL_OPTIONS: '-Dhttp.agent=curl/8.6.0 -Dextract.wikiapi.customUserAgent.enabled=true -Dextract.wikiapi.customUserAgent.text=curl/8.6.0' 
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run Maven install
        run: mvn install

      - name: Run MinidumpDoc
        working-directory: ./dump
        run: mvn package exec:java -Dexec.mainClass=org.dbpedia.extraction.dump.util.MinidumpDoc

      - name: Updating test coverage table
        uses: EndBug/add-and-commit@v4.4.0
        with:
          message: 'Github action minidumpdoc update'
          add: 'dump/src/test/resources/shaclTestsCoverageTable.md --force'
