name: Snapshot Deploy

on:
  push:
    branches: [ master ]  # or your development branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Set up settings.xml for deploy
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.GITHUB_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Deploy Snapshot
        env:
            GH_REPO_OWNER: ${{ github.repository_owner }}
            GH_REPO_NAME: ${{ github.event.repository.name }}
        run: mvn deploy -DskipTests -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/${GH_REPO_OWNER}/${GH_REPO_NAME}
